version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: training_app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 5

  backend:
    build: .
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://postgres:password@db:5432/training_app
      JWT_SECRET: production-super-secret-jwt-key-change-this-in-production
      PORT: 3000
      HOST: 0.0.0.0
      RUST_LOG: info
      ENVIRONMENT: production
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

volumes:
  postgres_data: